# ------------------------------------
# DATABASE CONNECTION (PostgreSQL)
# ------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin

# ------------------------------------
# JPA/Hibernate Settings (Optional but helpful)
# ------------------------------------
# Show the generated SQL in the console (helpful for debugging)
spring.jpa.show-sql=true 
# Control database schema generation (crucial for local development)
spring.jpa.hibernate.ddl-auto=update

# finnhub data provider (60 API calls/minute)
finnhub.baseUrl = https://finnhub.io/api/v1
finnhub.api.token = d42eropr01qorler208gd42eropr01qorler2090

# alphavantage data provider (25 API calls/day)
alphavantage.baseUrl = https://www.alphavantage.co
alphavantage.api.token = A1AUVL6TFBYF1GHF
